### ISSUE TITLE
lh command is not available after install

### ISSUE THREAD

**Issue by jney** [oh-my-fish/plugin-localhost#1]
i use latest version of omf and `lh` command is not available after install

**Comment by bpinto** [comment]
What is `lh` ?

**Comment by jney** [comment]
`lh` is the function provided by this plugin : https://github.com/oh-my-fish/plugin-localhost/blob/master/localhost.load#L17

**Comment by bpinto** [comment]
Err.. sorry! I was going through my notifications and didn't notice it.

**Comment by jkubecki** [comment]
If you go to `~/.local/share/omf/pkg/localhost` and rename `localhost.load` to `localhost.fish`, it works.

**Comment by bobthecow** [comment]
this is fixed by #2
